In [1]:
import keras.backend
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:
columns = ['user_id', 'item_id', 'rating', 'timestamp']
ratings = pd.read_csv('ml-100k/u.data', sep='\t', names=columns)
ratings.drop('timestamp', axis=1, inplace=True)
ratings.head()

user_id  item_id  rating
0      196      242       3
1      186      302       3
2       22      377       1
3      244       51       2
4      166      346       1

In [3]:
columns = ['item_id', 'movie title', 'release date', 'video release date', 'IMDb URL', 'unknown', 'Action', 'Adventure', 'Animation', 'Childrens', 'Comedy', 'Crime', 'Documentary', 'Drama', 'Fantasy', 'Film-Noir', 'Horror', 'Musical', 'Mystery', 'Romance', 'Sci-Fi', 'Thriller', 'War', 'Western']
movies = pd.read_csv('ml-100k/u.item', sep='|', names=columns, encoding='latin-1')
movies = movies[['item_id', 'movie title']]
movies.head()

item_id        movie title
0        1   Toy Story (1995)
1        2   GoldenEye (1995)
2        3  Four Rooms (1995)
3        4  Get Shorty (1995)
4        5     Copycat (1995)

In [6]:
user_movie_data = pd.merge(ratings, movies, on='item_id')
user_movie_data.head()

user_id  item_id  rating   movie title
0      196      242       3  Kolya (1996)
1       63      242       3  Kolya (1996)
2      226      242       5  Kolya (1996)
3      154      242       3  Kolya (1996)
4      306      242       5  Kolya (1996)

In [14]:
n_users = len(ratings['user_id'].unique())
n_items = len(movies['item_id'].unique())

In [15]:
print(n_users)
print(n_items)

943
1682


In [31]:
ratings = ratings.to_numpy()

In [7]:
user_movie_rating = user_movie_data.pivot_table('rating', index='user_id', columns='movie title').fillna(0)

In [17]:
rating_mat = np.zeros(shape= (n_users, n_items))

In [38]:
for u, i,  r in ratings:
    rating_mat[u-1, i-1] = r

In [39]:
rating_mat[0]

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 5., 3., ..., 0., 0., 0.],
       [0., 4., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [9]:
user_movie_rating.head()

movie title  'Til There Was You (1997)  1-900 (1994)  101 Dalmatians (1996)  \
user_id                                                                       
1                                  0.0           0.0                    2.0   
2                                  0.0           0.0                    0.0   
3                                  0.0           0.0                    0.0   
4                                  0.0           0.0                    0.0   
5                                  0.0           0.0                    2.0   

movie title  12 Angry Men (1957)  187 (1997)  2 Days in the Valley (1996)  \
user_id                                                                     
1                            5.0         0.0                          0.0   
2                            0.0         0.0                          0.0   
3                            0.0         2.0                          0.0   
4                            0.0         0.0                          0.0   
5                            0.0         0.0                          0.0   

movie title  20,000 Leagues Under the Sea (1954)  \
user_id                                            
1                                            3.0   
2                                            0.0   
3                                            0.0   
4                                            0.0   
5                                            0.0   

movie title  2001: A Space Odyssey (1968)  \
user_id                                     
1                                     4.0   
2                                     0.0   
3                                     0.0   
4                                     0.0   
5                                     4.0   

movie title  3 Ninjas: High Noon At Mega Mountain (1998)  \
user_id                                                    
1                                                    0.0   
2                                                    1.0   
3                                                    0.0   
4                                                    0.0   
5                                                    0.0   

movie title  39 Steps, The (1935)  ...  Yankee Zulu (1994)  \
user_id                            ...                       
1                             0.0  ...                 0.0   
2                             0.0  ...                 0.0   
3                             0.0  ...                 0.0   
4                             0.0  ...                 0.0   
5                             0.0  ...                 0.0   

movie title  Year of the Horse (1997)  You So Crazy (1994)  \
user_id                                                      
1                                 0.0                  0.0   
2                                 0.0                  0.0   
3                                 0.0                  0.0   
4                                 0.0                  0.0   
5                                 0.0                  0.0   

movie title  Young Frankenstein (1974)  Young Guns (1988)  \
user_id                                                     
1                                  5.0                3.0   
2                                  0.0                0.0   
3                                  0.0                0.0   
4                                  0.0                0.0   
5                                  4.0                0.0   

movie title  Young Guns II (1990)  Young Poisoner's Handbook, The (1995)  \
user_id                                                                    
1                             0.0                                    0.0   
2                             0.0                                    0.0   
3                             0.0                                    0.0   
4                             0.0                                    0.0   
5                             0.0                 

In [8]:
matrix = user_movie_rating.to_numpy()

In [9]:
matrix

array([[0., 0., 2., ..., 0., 4., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
print(user_movie_rating.columns.unique)

<bound method Index.unique of Index([''Til There Was You (1997)', '1-900 (1994)', '101 Dalmatians (1996)',
       '12 Angry Men (1957)', '187 (1997)', '2 Days in the Valley (1996)',
       '20,000 Leagues Under the Sea (1954)', '2001: A Space Odyssey (1968)',
       '3 Ninjas: High Noon At Mega Mountain (1998)', '39 Steps, The (1935)',
       ...
       'Yankee Zulu (1994)', 'Year of the Horse (1997)', 'You So Crazy (1994)',
       'Young Frankenstein (1974)', 'Young Guns (1988)',
       'Young Guns II (1990)', 'Young Poisoner's Handbook, The (1995)',
       'Zeus and Roxanne (1997)', 'unknown',
       'Á köldum klaka (Cold Fever) (1994)'],
      dtype='object', name='movie title', length=1664)>


In [30]:
n_movies = len(user_movie_rating.columns.unique())
print(n_movies)

1664


In [ ]:
U = np.zeros(shape=[n_movies, n_movies])

In [11]:
matrix[0].nonzero()

(array([   2,    3,    6,    7,   16,   17,   31,   35,   36,   41,   44,
          46,   50,   76,   84,   87,   88,   93,   94,  104,  109,  113,
         115,  127,  131,  133,  134,  143,  145,  152,  171,  175,  178,
         184,  199,  212,  223,  225,  226,  229,  230,  232,  238,  240,
         255,  262,  266,  293,  301,  303,  304,  313,  317,  321,  333,
         341,  349,  355,  360,  367,  369,  373,  389,  390,  400,  406,
         411,  412,  414,  415,  419,  420,  422,  426,  448,  450,  456,
         471,  475,  480,  498,  502,  517,  519,  524,  528,  532,  551,
         553,  554,  558,  559,  563,  567,  569,  570,  571,  572,  585,
         587,  591,  598,  608,  612,  613,  616,  618,  621,  622,  623,
         627,  628,  642,  643,  661,  672,  677,  690,  694,  696,  698,
         700,  711,  715,  728,  737,  744,  747,  773,  776,  780,  789,
         794,  797,  803,  811,  825,  827,  846,  850,  857,  867,  883,
         884,  891,  896,  909,  916, 

In [ ]:
for i in range(matrix[0].nonzero()):
    U[i]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
train, test = train_test_split(user_movie_data, test_size=0.2)

In [14]:
n_users = len(user_movie_data.user_id.unique())
n_movies = len(user_movie_data.item_id.unique())
n_latent_factors = 20

In [15]:
print(f'n_users:{n_users}, n_movies:{n_movies}, n_latent_factors:{n_latent_factors}')

n_users:943, n_movies:1682, n_latent_factors:20


In [16]:
import tensorflow as tf

In [17]:
tf.keras.backend.clear_session()

In [18]:
movie_input = tf.keras.layers.Input(shape=[1], name="Item")
movie_embedding = tf.keras.layers.Embedding(n_movies+1, n_latent_factors, name="Movie-Embedding")(movie_input)
movie_vec = tf.keras.layers.Flatten(name="FlattenMovies")(movie_embedding)

In [19]:
user_input = tf.keras.layers.Input(shape=[1], name="User")
user_embedding = tf.keras.layers.Embedding(n_users+1, n_latent_factors, name="User-Embedding")(user_input)
user_vec = tf.keras.layers.Flatten(name="FlattenUsers")(user_embedding)

In [20]:
prod = tf.keras.layers.dot([movie_vec, user_vec], axes=1, name='DotProduct')
model = tf.keras.Model([user_input, movie_input], prod)

In [21]:
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae', 'mse'])
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 Item (InputLayer)              [(None, 1)]          0           []                               
                                                                                                  
 User (InputLayer)              [(None, 1)]          0           []                               
                                                                                                  
 Movie-Embedding (Embedding)    (None, 1, 20)        33660       ['Item[0][0]']                   
                                                                                                  
 User-Embedding (Embedding)     (None, 1, 20)        18880       ['User[0][0]']                   
                                                                                              

In [22]:
history = model.fit([train.user_id, train.item_id], train.rating, batch_size=32, epochs=150, verbose=1)

Epoch 1/150
1979/2500 [======================>.......] - ETA: 3s - loss: 10.4496 - mae: 2.9606 - mse: 10.4496

KeyboardInterrupt: 

In [ ]:
tf.keras.backend.clear_session()

In [ ]:
model.save("trained.h5")

In [23]:
model.load_weights("trained.h5")